### ISSUE TITLE
노트 수정 후 `/notes/[goalId]` 페이지 데이터 업데이트 안 됨

### ISSUE THREAD

**Issue by forestream** [FESI-4-4/slid-todo#147]
## 이슈 내용
노트 수정 후 `/notes/[goalId]` 페이지 데이터 업데이트 안 됨
넥스트 캐시와 탠스택 쿼리 캐시에 적절한 수정이 필요해보입니다.

**Comment by ahrrrl** [comment]
useNoteMutation.ts 파일에 성공했을 시  queryClient.invalidateQueries({ queryKey: ['notes'] });로 키값을 invalidate 해주시면 될겁니다!
