### ISSUE TITLE
[ 목표 ] 대시보드, NAV, 새 할일 모달의 목표 셀렉터에서 목표가 동일하게 업데이트 되지 않는 오류

### ISSUE THREAD

**Issue by MinaRoh** [FESI-4-4/slid-todo#373]
## 이슈 내용
- nav로 목표 삭제시 대시보드 최근 할일에 여전히 해당 할일과 목표가 남아있는 오류
- nav로 목표 추가 후 간헐적으로 새 할일 모달에 해당 목표가 보이지 않는 오류

## ✅ To Dos

- [x] nav 목표 추가/삭제 이후 invalidateQueries 혹은 refetchQueries 추가

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified useAddGoalMutation and useDeleteGoalMutation hooks to invalidate and refetch the 'todos' query along with the 'goals' query. This ensures that the dashboard's recent todos are updated when goals are added or deleted.

You can review changes in this commit: https://github.com/mnmnk43434/FESI-4-4-slid-todo-373/commit/067b313cbb69525e587075f6351af4838ef9ae5a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
